package cli

// R29 query grpc-routes 测试：服务端路由清单——grpc_service 节点 →
// Register 函数（生成代码文件）→ ServiceDesc 方法列表 + grpc_impl
// 实现类型 + 注册调用点。测试先行（待办 1 grpc 部分）。

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/schaepher/codeintel/internal/domain"
	"github.com/schaepher/codeintel/internal/infrastructure/sqlite"
)

// seedGrpcRoutesRepo 构造含 grpc 服务端数据的索引 + 生成代码文件：
// grpc_service 节点（svc.QueryService）+ grpc_impl 边 + Register 函数
// 节点 + main→Register 调用边（line 34）+ 真实 ServiceDesc 生成代码。
func seedGrpcRoutesRepo(t *testing.T) string {
	t.Helper()
	dir := seedRepo(t) // go.mod + main 节点 + main→(Svc).Run 边
	// 生成代码文件（ServiceDesc 形态与 protoc 一致）
	pb := `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package grpc

import "google.golang.org/grpc"

type QueryServiceServer interface {
	Query(ctx interface{}, req interface{}) (interface{}, error)
}

var QueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Query", Handler: _QueryService_Query_Handler},
		{MethodName: "PagingShops", Handler: _QueryService_PagingShops_Handler},
	},
	Streams: []grpc.StreamDesc{},
}

func RegisterQueryServiceServer(s grpc.ServiceRegistrar, srv QueryServiceServer) {}

func _QueryService_Query_Handler(srv interface{}, ctx interface{}) error { return nil }
func _QueryService_PagingShops_Handler(srv interface{}, ctx interface{}) error { return nil }
`
	if err := os.MkdirAll(filepath.Join(dir, "grpc"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "grpc/query_grpc.pb.go"), []byte(pb), 0o644); err != nil {
		t.Fatal(err)
	}

	db, err := sqlite.Open(dir)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	r := sqlite.NewRepo(db)
	nodes := []*domain.CodeEntity{
		// 服务节点（markServiceEntry 注册点建立）
		{ID: "symbol:go:example.com/m/grpc:svc.QueryService", Kind: domain.KindGrpcService,
			Name: "svc.QueryService", FilePath: "grpc/query_grpc.pb.go",
			Properties: map[string]any{"service_name": "QueryService"}},
		// 服务接口（注册参数为接口——inject 注入器形态；grpc_impl source）
		{ID: "symbol:go:example.com/m/grpc:QueryServiceServer", Kind: domain.KindInterface,
			Name: "QueryServiceServer", FilePath: "grpc/query_grpc.pb.go", LineStart: 10},
		// 服务实现（implements 边：接口 → 实现者）
		{ID: "symbol:go:example.com/m/impl:queryServiceImpl", Kind: domain.KindStruct,
			Name: "queryServiceImpl", FilePath: "impl/query.go", LineStart: 20},
		// 注册函数（签名识别建立——registers_service 属性；R30 不再按名查）
		{ID: "symbol:go:example.com/m/grpc:RegisterQueryServiceServer", Kind: domain.KindFunction,
			Name: "RegisterQueryServiceServer", FilePath: "grpc/query_grpc.pb.go", LineStart: 41,
			Properties: map[string]any{"registers_service": "QueryService"}},
		// 注册调用点函数（serves_grpc 标记的调用者——serviceFlags 写回）
		{ID: "symbol:go:example.com/m/grpc:setupGrpc", Kind: domain.KindFunction,
			Name: "setupGrpc", FilePath: "grpc/server.go", LineStart: 18,
			Properties: map[string]any{"serves_grpc": "true"}},
	}
	if _, err := r.SaveBatchStats(nodes, nil, nil); err != nil {
		t.Fatalf("save nodes: %v", err)
	}
	facts := []*domain.Fact{
		// grpc_impl：注册参数类型（接口）→ 服务
		{SourceID: "symbol:go:example.com/m/grpc:QueryServiceServer", TargetID: "symbol:go:example.com/m/grpc:svc.QueryService",
			Kind: domain.FactGrpcImpl, Confidence: 1.0},
		// implements：接口 → 实现 struct（SCIP is_implementation）
		{SourceID: "symbol:go:example.com/m/grpc:QueryServiceServer", TargetID: "symbol:go:example.com/m/impl:queryServiceImpl",
			Kind: domain.FactImplements, Confidence: 1.0},
		// 注册调用：setupGrpc → RegisterQueryServiceServer（行 34）
		{SourceID: "symbol:go:example.com/m/grpc:setupGrpc", TargetID: "symbol:go:example.com/m/grpc:RegisterQueryServiceServer",
			Kind: domain.FactCalls, Confidence: 0.8, Metadata: map[string]any{"line_num": 34}},
	}
	if _, err := r.SaveBatchStats(nil, facts, nil); err != nil {
		t.Fatalf("save facts: %v", err)
	}
	return dir
}

// TestQueryGrpcRoutes：JSON 契约——服务名/实现/注册调用点/方法列表
// （ServiceDesc parser 提取全量方法，含 handler）。
func TestQueryGrpcRoutes(t *testing.T) {
	dir := seedGrpcRoutesRepo(t)
	db, err := sqlite.Open(dir)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	out, err := grpcRoutes(sqlite.NewRepo(db), dir)
	if err != nil {
		t.Fatalf("grpcRoutes: %v", err)
	}
	if len(out.Services) != 1 {
		t.Fatalf("服务数 = %d; want 1:\n%+v", len(out.Services), out)
	}
	s := out.Services[0]
	if s.Name != "QueryService" {
		t.Errorf("name = %q; want QueryService", s.Name)
	}
	if s.Impl != "queryServiceImpl" {
		t.Errorf("impl = %q; want queryServiceImpl（grpc_impl 边）", s.Impl)
	}
	if !strings.Contains(s.ImplFile, "impl/query.go") {
		t.Errorf("impl_file = %q; want impl/query.go", s.ImplFile)
	}
	if s.Register != "grpc/server.go:34" {
		t.Errorf("register = %q; want grpc/server.go:34（调用边 line_num）", s.Register)
	}
	if len(s.Methods) != 2 {
		t.Fatalf("方法数 = %d; want 2（ServiceDesc 全量，非 grpc_call 子集）:\n%+v", len(s.Methods), s.Methods)
	}
	if s.Methods[0].Name != "Query" || s.Methods[0].Handler != "_QueryService_Query_Handler" {
		t.Errorf("methods[0] = %+v; want Query/_QueryService_Query_Handler", s.Methods[0])
	}
	if s.Methods[1].Name != "PagingShops" {
		t.Errorf("methods[1] = %+v; want PagingShops", s.Methods[1])
	}
	// JSON 序列化契约（Q5）——字段名可被 Agent 解析
	b, err := json.Marshal(out)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{`"name":"QueryService"`, `"impl":"queryServiceImpl"`, `"methods"`, `"handler"`, `"register"`} {
		if !strings.Contains(string(b), want) {
			t.Errorf("JSON 缺 %q:\n%s", want, b)
		}
	}
}
